# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0

      - name: Grant execute permission to Root Gradle Wrapper
        run: chmod +x gradlew

      - name: Grant execute permission to 1_21_4 Gradle Wrapper
        run: |
          cd "/home/runner/work/MCVersionRenamer/MCVersionRenamer/mcvr_1214"
          chmod +x gradlew

      - name: Grant execute permission to 1_21_5 Gradle Wrapper
        run: |
          cd "/home/runner/work/MCVersionRenamer/MCVersionRenamer/mcvr_1215"
          chmod +x gradlew

      - name: Build root
        run: ./gradlew build

      - name: Build 1_21_4
        run: |
          cd "/home/runner/work/MCVersionRenamer/MCVersionRenamer/mcvr_1214"
          ./gradlew build

      - name: Build 1_21_5
        run: |
          cd "/home/runner/work/MCVersionRenamer/MCVersionRenamer/mcvr_1215"
          ./gradlew build

      - name: Upload Root Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: root
          path: /home/runner/work/MCVersionRenamer/MCVersionRenamer/build/libs/**.jar

      - name: Upload 1_21_4 Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: 1_21_4
          path: /home/runner/work/MCVersionRenamer/MCVersionRenamer/mcvr_1214/build/libs/**.jar

      - name: Upload 1_21_5 Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: 1_21_5
          path: /home/runner/work/MCVersionRenamer/MCVersionRenamer/mcvr_1215/build/libs/**.jar